### ISSUE TITLE
Return inside loop causing it runs exactly once

### ISSUE THREAD

**Issue by shrr98** [Anthony-Suryajaya/Tugas_Akhir#3]
This return statement causes the code inside 'while' executed once:
https://github.com/Anthony-Suryajaya/Tugas_Akhir/blob/6214ea759f8ae65534ea3590a2973037357c046d/TA_CAS_OD.py#L43

As above function uses while loop, this line will cause the code stuck. Moving the execution to a new thread could help.
https://github.com/Anthony-Suryajaya/Tugas_Akhir/blob/6214ea759f8ae65534ea3590a2973037357c046d/TA_CAS_OD.py#L217

**Comment by Anthony-Suryajaya** [comment]
Issue fixed by changing the power source to a higher current and simplfiying the code within the `while True` loophttps://user-images.githubusercontent.com/92085498/168734999-977fc8ba-7b75-4c35-b68d-a5383243b46e.mp4
